config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  scope module: 'web' do
    root 'bulletins#index'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    get '/logout', to: 'auth#destroy', as: 'logout'
    resource :profile, controller: 'users', action: 'show', as: 'profile'
    resources :bulletins do
      member do
        patch :send_for_moderation
        patch :archive
      end
    end
    namespace :admin do
      get '/', to: 'bulletins#admin'
      resources :categories
      resources :bulletins, only: %i[index show] do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
        collection do
          get 'moderation'
        end
      end
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :bulletins, dependent: :destroy
end

app/controllers/web/users_controller.rb
# frozen_string_literal: true

class Web::UsersController < Web::ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @q = Bulletin.ransack(params[:q])

    @bulletins = current_user.bulletins
                             .ransack(params[:q])
                             .result
                             .order(created_at: :desc)
                             .page(params[:page]).per(10)
  end
end

app/views/user/show.html.slim
h1.text-center = t('bulletin.bulletins')

.container.mt-4
  .card.bg-light
    .card-body
      = search_form_for @q, url: profile_path, method: :get, class: 'form-inline' do |f|
        .row
          .col-md-3
            .form-group
              = f.label :title_cont, t('search.name')
              = f.text_field :title_cont, class: 'form-control', placeholder: t('bulletin.name')
          .col-md-3
            .form-group
              = f.label :state_cont, t('search.state')
              = f.select :state_cont,
               options_for_select([['Published', :published], ['Draft', :draft], ['Archived', :archived], ['Rejected', :rejected], ['On moderation', :under_moderation]],
               selected: params.dig(:q, :state_cont)), { include_blank: true }, class: 'form-control', placeholder: t('bulletin.state')
          .col-md-3
            .form-group.mt-md-4
              = f.submit t('search.find'), class: 'btn btn-primary mt-4 mt-md-0'
          .col-md-3
            .form-group.mt-md-4
              = link_to t('search.reset'), profile_path, class: 'btn btn-secondary mt-4 mt-md-0'

- if @bulletins.empty?
  p = t('bulletin.empty')
- else
  table.table.table-striped
    thead
      tr
        th.h5 = t('bulletin.title')
        th.h5 = t('bulletin.state')
        th.h5 = t('bulletin.actions')
    tbody
      - @bulletins.each do |bulletin|
        tr.font-weight-bold

          td.h4 = link_to bulletin.title, bulletin_path(bulletin)
          td.h4 = bulletin.state.humanize
          td
            = link_to t('bulletin.show'), bulletin_path(bulletin), class: 'btn btn-info'
            - if bulletin.state == 'draft'
              = button_to t('button.moderate'), send_for_moderation_bulletin_path(bulletin), method: :post, class: 'btn btn-warning'
              = button_to t('button.archive'), archive_bulletin_path(bulletin), method: :patch, data: { turbo_confirm: t('destroy.confirm') }, class: 'btn btn-danger'
            - if bulletin.state == 'published'
              = button_to t('button.archive'), archive_bulletin_path(bulletin), method: :patch, data: { turbo_confirm: t('destroy.confirm') }, class: 'btn btn-secondary'
            - if bulletin.state == 'rejected'
              = button_to t('button.archive'), archive_bulletin_path(bulletin), method: :patch, data: { turbo_confirm: t('destroy.confirm') }, class: 'btn btn-secondary'
.pagination-wrapper
  .pagination
    = paginate @bulletins

= link_to t('bulletin.create'), new_bulletin_path, class: 'btn btn-success mt-4'