config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  scope module: 'web' do
    root 'bulletins#index'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    get '/logout', to: 'auth#destroy', as: 'logout'
    resource :profile, controller: 'users', action: 'show', as: 'profile'
    resources :bulletins do
      member do
        patch :send_for_moderation
        patch :archive
      end
    end
    namespace :admin do
      get '/', to: 'bulletins#admin'
      resources :categories
      resources :bulletins, only: %i[index show] do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
        collection do
          get 'moderation'
        end
      end
    end
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :bulletins, dependent: :restrict_with_error
  validates :name, presence: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[name id]
  end
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

class Admin::CategoriesController < ApplicationController
  before_action :authorize_admin

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path, notice: I18n.t('flash.update', model: @bulletin.class.name)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path, notice: I18n.t('flash.destroy', model: @bulletin.class.name)
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end

  def authorize_admin
    redirect_to root_path, alert: I18n.t('admin.not_auth') unless current_user&.user_admin?
  end
end

app/controllers/web/admin/categories_controller.rb
# frozen_string_literal: true

class Web::Admin::CategoriesController < Web::Admin::ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to admin_categories_path, notice: I18n.t('category.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path, notice: I18n.t('flash.update', model: @category.class.name)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.bulletins.exists?
      redirect_to admin_categories_path, alert: I18n.t('category.referenced')
    else
      @category.destroy
      redirect_to admin_categories_path, notice: I18n.t('flash.destroy', model: @category.class.name)
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/web/admin/categories/_category.html.slim
.category{style: margin-left: level * 20 px;}
  div id=dom_id(category)
    p.h3.text-left
      = category.name

app/views/web/admin/categories/_form.html.slim
- if category.errors.any?
  .alert.alert-danger
    - category.errors.full_messages.each do |message|
      li = message

= form_with(model: category, url: category.persisted? ? admin_category_path(category) : admin_categories_path) do |form|

  .form-group
    = form.text_field :name, class: 'form-control', placeholder: t('category.name')
  p
  .form-group
    = form.submit t('submit'), class: 'btn btn-primary'

app/views/web/admin/categories/edit.html.slim
h1 = t('category.edit')

= render 'web/admin/categories/form', category: @category

app/views/web/admin/categories/index.html.slim
h1 class="text-center" = t('category.categories')

.categories
  - @categories.each do |category|
    .category-item
      = render category
      p.text-left
        = link_to t('category.show'), admin_category_path(category), class: 'btn btn-primary btn-lg'
        = link_to t('category.edit'), edit_admin_category_path(category), class: 'btn btn-warning btn-lg'
        = link_to t('category.delete'), admin_category_path(category), data: { turbo_method: :delete, turbo_confirm: t('destroy.confirm') }, class: 'btn btn-danger btn-lg'

= link_to t('category.new'), new_admin_category_path, class: 'btn btn-success btn-lg'

app/views/web/admin/categories/new.html.slim
h1 = t('category.new')

= render 'web/admin/categories/form', category: @category

app/views/web/admin/categories/show.html.slim
= render 'web/admin/categories/category', category: @category

- if @category.bulletins.any?
  ul.list-group
    - @category.bulletins.each do |bulletin|
      li.list-group-item
        = link_to bulletin.title, admin_bulletin_path(bulletin), class: 'text-decoration-none h5'

.mt-3
  = link_to t('category.back'), admin_categories_path, class: 'btn btn-primary btn-lg'