config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  scope module: 'web' do
    root 'bulletins#index'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    get '/logout', to: 'auth#destroy', as: 'logout'
    resource :profile, controller: 'users', action: 'show', as: 'profile'
    resources :bulletins do
      member do
        patch :send_for_moderation
        patch :archive
      end
    end
    namespace :admin do
      get '/', to: 'bulletins#admin'
      resources :categories
      resources :bulletins, only: %i[index show] do
        member do
          patch :publish
          patch :reject
          patch :archive
        end
        collection do
          get 'moderation'
        end
      end
    end
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
    meta[name='viewport' content='width=device-width,initial-scale=1']
    meta[name='apple-mobile-web-app-capable' content='yes']
    = csrf_meta_tags
    = csp_meta_tag
    link[rel='manifest' href='/manifest.json']
    link[rel='icon' href='/icon.png' type='image/png']
    link[rel='icon' href='/icon.svg' type='image/svg+xml']
    link[rel='apple-touch-icon' href='/icon.png']
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
  body
    - flash.each do |key, message|
      - if key == 'notice'
        .alert.alert-success.border-success
          = message
      - elsif key == 'alert'
        .alert.alert-danger.border-danger.role = alert
          = message

    .page-container
      header.navbar.navbar-expand-lg.navbar-light.bg-light
        nav.container-fluid
          .navbar-header.d-flex.align-items-center
            = link_to t('user.home'), root_path, class: 'navbar-brand text-primary text-decoration-none'
            - if current_user
              = link_to t('bulletin.create'), new_bulletin_path, class: 'navbar-brand text-primary text-decoration-none'
          - if current_user&.admin?
            = link_to t('user.admin'), admin_path, class: 'navbar-brand text-primary text-decoration-none'

          - if user_signed_in?
            = link_to t('user.profile'), profile_path, class: 'navbar-brand text-primary text-decoration-none'
            = link_to t('user.logout'), logout_path, method: :delete, class: 'navbar-brand text-primary text-decoration-none'
            .ms-auto.d-flex.align-items-center
              .navbar-text.text-primary.font-weight-bold.fs-4
                = current_user.email
          - else
            = button_to t('user.login'), auth_request_path('github'), data: { turbo: false }, method: :post, class: 'navbar-brand text-primary text-decoration-none'

      main.container-fluid
        = yield
      footer
        .container
          p &copy; 2025 Bulletin Desk